services:
  frontend:
    image: europe-southwest1-docker.pkg.dev/utopian-honor-438919-b9/invoiceapp/servitec-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:8080"
    environment:
      - PORT=8080
      - REACT_APP_API_URL=https://servitec-backend-62676166363.europe-southwest1.run.app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: europe-southwest1-docker.pkg.dev/utopian-honor-438919-b9/invoiceapp/servitec-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
      - DB_HOST=34.175.125.26
      - DB_PORT=5432
      - DB_NAME=ServitecInvoiceData
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - INSTANCE_CONNECTION_NAME=utopian-honor-438919-b9:europe-southwest1:servitec-invoices
      - PORT=8080
      - VPN_SUBNET=${VPN_SUBNET}
    ports:
      - "5000:8080"
    volumes:
      - /cloudsql:/cloudsql
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
